//! P1 perft parity gate (docs/plans/PLAN_03_rust_port.md "Parity
//! verification"). Fixture is generated by `tools/js/perft.mjs` from the
//! JS oracle (`frontend/game.js` + `frontend/rules.js`); regenerate with:
//!
//! ```sh
//! node tools/js/perft.mjs > crates/shatrunz-core/tests/fixtures/perft_fixture.json
//! ```

use serde::Deserialize;
use shatrunz_core::game::Game;
use shatrunz_core::moves::{MoveTarget, Square};

#[derive(Debug, Deserialize)]
struct Fixture {
    startpos: StartposCounts,
    seeded: Vec<SeededCase>,
}

#[derive(Debug, Deserialize)]
struct StartposCounts {
    depth1: u64,
    depth2: u64,
    depth3: u64,
}

#[derive(Debug, Deserialize)]
struct SeededCase {
    #[allow(dead_code)]
    seed: u64,
    path: Vec<FixtureMove>,
    depth: u32,
    nodes: u64,
    position_key: String,
}

#[derive(Debug, Deserialize)]
struct FixtureSquare {
    r: usize,
    c: usize,
}

#[derive(Debug, Deserialize)]
struct FixtureMove {
    from: FixtureSquare,
    to: FixtureTo,
}

#[derive(Debug, Deserialize)]
struct FixtureTo {
    r: usize,
    c: usize,
    #[serde(rename = "isCastling")]
    is_castling: bool,
}

fn load_fixture() -> Fixture {
    let raw = include_str!("fixtures/perft_fixture.json");
    serde_json::from_str(raw).expect("perft_fixture.json must parse")
}

fn perft(game: &mut Game, depth: u32) -> u64 {
    if depth == 0 {
        return 1;
    }
    let moves = game.legal_moves(game.turn);
    let mut nodes = 0u64;
    for m in moves {
        game.execute_move(m.from, m.to);
        nodes += perft(game, depth - 1);
        assert!(game.undo_last_move());
    }
    nodes
}

#[test]
fn perft_startpos_matches_js_oracle() {
    let fixture = load_fixture();
    let mut game = Game::new();
    assert_eq!(perft(&mut game, 1), fixture.startpos.depth1);
    assert_eq!(perft(&mut game, 2), fixture.startpos.depth2);
    assert_eq!(perft(&mut game, 3), fixture.startpos.depth3);
}

#[test]
fn perft_seeded_positions_match_js_oracle() {
    let fixture = load_fixture();
    for case in &fixture.seeded {
        let mut game = Game::new();
        for mv in &case.path {
            let from = Square { r: mv.from.r, c: mv.from.c };
            let to = MoveTarget {
                r: mv.to.r,
                c: mv.to.c,
                is_castling: mv.to.is_castling,
                castling_side: None,
            };
            let ok = game.execute_move(from, to);
            assert!(ok, "seed {}: replaying opening move failed", case.seed);
        }
        assert_eq!(
            game.position_key(),
            case.position_key,
            "seed {}: position_key mismatch after replaying opening",
            case.seed
        );
        let nodes = perft(&mut game, case.depth);
        assert_eq!(
            nodes, case.nodes,
            "seed {}: perft(depth={}) mismatch",
            case.seed, case.depth
        );
    }
}
