//! P3 search parity gate, persona side (docs/plans/PLAN_03_rust_port.md
//! "Parity verification"): deterministic config (no randomness/bonuses/
//! deadline, fixed depth 2-3), bestmove+score JS vs Rust. Fixture is
//! generated by driving the *real* `frontend/ai.js`/`frontend/brain.js`
//! code (not a reimplementation) with an in-memory localStorage/document
//! polyfill so brain state is always empty. Regenerate with:
//!
//! ```sh
//! node tools/js/search_persona_dump.mjs > crates/shatrunz-core/tests/fixtures/search_persona_fixture.json
//! ```

use serde::Deserialize;
use shatrunz_core::eval::hce::Persona;
use shatrunz_core::game::Game;
use shatrunz_core::moves::{Move, MoveTarget, Square};
use shatrunz_core::piece::PieceKind;
use shatrunz_core::search::persona::{get_best_move, SearchConfig};

#[derive(Debug, Deserialize)]
struct Fixture {
    positions: Vec<PositionCase>,
}

#[derive(Debug, Deserialize)]
struct PositionCase {
    label: String,
    #[serde(rename = "uciMoves")]
    uci_moves: Vec<String>,
    results: Results,
}

#[derive(Debug, Deserialize)]
struct Results {
    material: PersonaResults,
    positional: PersonaResults,
    aggressive: PersonaResults,
}

#[derive(Debug, Deserialize)]
struct PersonaResults {
    depth2: DepthResultFixture,
    depth3: DepthResultFixture,
}

#[derive(Debug, Deserialize)]
struct DepthResultFixture {
    uci: Option<String>,
    #[serde(rename = "bestScore")]
    best_score: f64,
    #[serde(rename = "secondScore")]
    second_score: f64,
    #[serde(rename = "depthReached")]
    depth_reached: u32,
}

fn load_fixture() -> Fixture {
    let raw = include_str!("fixtures/search_persona_fixture.json");
    serde_json::from_str(raw).expect("search_persona_fixture.json must parse")
}

fn parse_uci(uci: &str) -> (Square, MoveTarget) {
    let bytes = uci.as_bytes();
    let from_file = (bytes[0] - b'a') as usize;
    let from_rank: usize = (bytes[1] - b'0') as usize;
    let to_file = (bytes[2] - b'a') as usize;
    let to_rank: usize = (bytes[3] - b'0') as usize;
    let from = Square { r: 9 - from_rank, c: from_file };
    let to = MoveTarget::plain(9 - to_rank, to_file);
    (from, to)
}

/// Mirrors `moveToUCI` (frontend/shared/uci.js:25-40): file a-i,
/// rank = 9-row, `q` suffix for auto-queen promotion.
fn move_to_uci(game: &Game, m: Move) -> String {
    const FILES: &[u8] = b"abcdefghi";
    let from_file = FILES[m.from.c] as char;
    let to_file = FILES[m.to.c] as char;
    let from_rank = 9 - m.from.r;
    let to_rank = 9 - m.to.r;
    let moved = game.board.get(m.from.r, m.from.c);
    let promo = if matches!(moved, Some(p) if p.kind == PieceKind::Pawn) && (m.to.r == 0 || m.to.r == 8) {
        "q"
    } else {
        ""
    };
    format!("{from_file}{from_rank}{to_file}{to_rank}{promo}")
}

#[test]
fn persona_search_matches_js_oracle() {
    let fixture = load_fixture();
    for case in &fixture.positions {
        let mut game = Game::new();
        for uci in &case.uci_moves {
            let (from, to) = parse_uci(uci);
            assert!(game.execute_move(from, to), "{}: replay move {uci} failed", case.label);
        }

        for (persona, results) in [
            (Persona::Material, &case.results.material),
            (Persona::Positional, &case.results.positional),
            (Persona::Aggressive, &case.results.aggressive),
        ] {
            for (base_depth, expected) in [(2u32, &results.depth2), (3u32, &results.depth3)] {
                let cfg = SearchConfig {
                    persona,
                    add_randomness: false,
                    deadline: None,
                };
                let turn = game.turn;
                let result = get_best_move(&mut game, turn, base_depth, &cfg, &|_m| 0.0);

                let ctx = format!("{} {:?} depth{}", case.label, persona, base_depth);
                assert_eq!(result.depth_reached, expected.depth_reached, "{ctx}: depth_reached");
                assert_eq!(result.best_score, expected.best_score, "{ctx}: best_score");
                assert_eq!(result.second_score, expected.second_score, "{ctx}: second_score");
                match (result.best_move, &expected.uci) {
                    (Some(m), Some(expected_uci)) => {
                        assert_eq!(&move_to_uci(&game, m), expected_uci, "{ctx}: best_move uci");
                    }
                    (None, None) => {}
                    (got, want) => panic!("{ctx}: best_move mismatch: got {got:?}, want {want:?}"),
                }
            }
        }
    }
}
